export enum RoutePath {
  HOME = "/",
  LOGIN = "/login",
  HOMEPAGE = "/homepage/:id",
  SIGNUP = "/signup",
  PROFILE = "/profile/:id",
  CREATEGAME = "/creategame",
  CREATEGENRE = "/creategenre",
  CREATEPROFILE = "/createprofile",
  CREATEUSER = "/createuser",
  GAMEDETAILS = "/gamedetails/:id",
  EDITUSER = "/edituser/:id",
  EDITGAME = "/editgame/:id",
  EDITGENRE = "/editgenre/:id",
  EDITPROFILE = "/editprofile/:id",
}
